# Just runs npm start script in development mode.

FROM node:lts-alpine
WORKDIR /app
COPY package.json ./
RUN npm ci 
COPY ./ ./

FROM nginx:stable-alpine as prod
COPY --from=build /app/build usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]