# Just runs npm start script in development mode.

FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npm install react-scripts@4.0.3 -g

COPY . ./

EXPOSE 8080

ENV CHOKIDAR_USEPOLLING=true

CMD ["node", "app.js"]