name: Base Image Options

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu latest
    steps:
      - uses: actions/checkout@v2
      - name: single-command
        run: echo Hello out there!


