name: Base Image Options

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: single-command
        run: echo Hello out there!

      - name: multi-line
        run: |
          echo ls
          echo
          echo java -version
          echo
          echo git --version
          echo
          echo mvn -v
          echo
          echo gradle -version
          echo
          echo ant -version
          echo
          echo $ANDROID_SDK_ROOT
          echo
          echo $SELENIUM_JARS
          echo
          echo $RUNNER_WORKSPACE
          echo
          echo whoami
          echo
          echo df
          echo
          echo env -0 | sort -z | tr '\0' '\n'
