- name: multi-line
  run: |
    echo ls
    echo java -version
    echo git --version
    echo mvn -v
    echo gradle -version
    echo ant -version
    echo $ANDROID_SDK_ROOT
    echo $SELENIUM_JARS
    echo $RUNNER_WORKSPACE
    echo whoami
    echo df
    echo env-0 | sort -z | tr '\0' \n'
